// Ansible playbook generator for archlet diagrams
import { sanitizeName, cfg, topoSort, type IacNode, type IacEdge } from "./utils";

const HEADER = `# Generated by archlet — Ansible playbook starter
# Adapt to role-style layout for production use
# Requires: ansible-galaxy collection install community.docker
---
`;

function containerTask(name: string, image: string, ports: string[], env: Record<string, string>, extraOpts: Record<string, unknown> = {}): string {
  const envLines = Object.entries(env)
    .map(([k, v]) => `        ${k}: "${v}"`)
    .join("\n");

  const portsYaml = ports.map((p) => `        - "${p}"`).join("\n");

  const extraLines = Object.entries(extraOpts)
    .map(([k, v]) => {
      if (typeof v === "string") return `      ${k}: "${v}"`;
      return `      ${k}: ${JSON.stringify(v)}`;
    })
    .join("\n");

  return [
    `    - name: Run ${name}`,
    `      community.docker.docker_container:`,
    `        name: ${name}`,
    `        image: ${image}`,
    `        state: started`,
    `        restart_policy: unless-stopped`,
    portsYaml ? `        published_ports:\n${portsYaml}` : "",
    envLines ? `        env:\n${envLines}` : "",
    extraLines,
  ].filter(Boolean).join("\n");
}

function commentTask(name: string, note: string): string {
  return `    # SKIP ${name}: ${note}`;
}

function nodeToTask(node: IacNode): string {
  const name = sanitizeName(node.data.label);
  const variant = node.data.variant ?? "";
  const type = node.type ?? "";
  const config = node.data.config ?? {};

  if (type === "database") {
    if (variant === "postgres") {
      const version = cfg(config, "version", "16");
      return containerTask(name, `postgres:${version}`, ["5432:5432"], {
        POSTGRES_PASSWORD: "{{ postgres_password | default('change_me') }}",
        POSTGRES_DB: name,
      }, { volumes: [`${name}_data:/var/lib/postgresql/data`] });
    }
    if (variant === "mysql") {
      const version = cfg(config, "version", "8.0");
      return containerTask(name, `mysql:${version}`, ["3306:3306"], {
        MYSQL_ROOT_PASSWORD: "{{ mysql_password | default('change_me') }}",
        MYSQL_DATABASE: name,
      }, { volumes: [`${name}_data:/var/lib/mysql`] });
    }
    if (variant === "mongodb") {
      const version = cfg(config, "version", "7.0");
      return containerTask(name, `mongo:${version}`, ["27017:27017"], {
        MONGO_INITDB_ROOT_USERNAME: "admin",
        MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_password | default('change_me') }}",
      }, { volumes: [`${name}_data:/data/db`] });
    }
    if (variant === "cassandra") {
      return containerTask(name, "cassandra:4", ["9042:9042"], {}, {
        volumes: [`${name}_data:/var/lib/cassandra`],
      });
    }
    return commentTask(name, `${variant} — provision via managed cloud service`);
  }

  if (type === "cache") {
    if (variant === "redis") {
      const memGb = cfg<number>(config, "memoryGb", 1);
      const policy = cfg(config, "evictionPolicy", "allkeys-lru");
      return containerTask(name, "redis:7-alpine", ["6379:6379"], {}, {
        command: `redis-server --maxmemory ${memGb}gb --maxmemory-policy ${policy}`,
      });
    }
    if (variant === "memcached") {
      const memMb = cfg<number>(config, "memoryMb", 512);
      return containerTask(name, "memcached:alpine", ["11211:11211"], {}, {
        command: `memcached -m ${memMb}`,
      });
    }
    return containerTask(name, `${variant}:latest`, ["6379:6379"], {});
  }

  if (type === "queue") {
    if (variant === "rabbitmq") {
      return containerTask(name, "rabbitmq:3-management", ["5672:5672", "15672:15672"], {
        RABBITMQ_DEFAULT_USER: "admin",
        RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_password | default('change_me') }}",
      });
    }
    if (variant === "kafka") {
      const partitions = cfg<number>(config, "partitions", 12);
      return [
        containerTask("zookeeper", "confluentinc/cp-zookeeper:7.5.0", ["2181:2181"], {
          ZOOKEEPER_CLIENT_PORT: "2181",
          ZOOKEEPER_TICK_TIME: "2000",
        }),
        containerTask(name, "confluentinc/cp-kafka:7.5.0", ["9092:9092"], {
          KAFKA_BROKER_ID: "1",
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181",
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092",
          KAFKA_NUM_PARTITIONS: String(partitions),
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1",
        }),
      ].join("\n\n");
    }
    return commentTask(name, `${variant} — use managed cloud queue service`);
  }

  if (type === "storage") {
    if (variant === "local-disk") {
      const sizeGb = cfg<number>(config, "sizeGb", 100);
      return [
        `    - name: Ensure data directory for ${name}`,
        `      ansible.builtin.file:`,
        `        path: /data/${name}`,
        `        state: directory`,
        `        mode: '0755'`,
        `      # local-disk: ${sizeGb}GB target`,
      ].join("\n");
    }
    return commentTask(name, `${variant} — configure via cloud provider SDK/CLI`);
  }

  if (type === "load_balancer") {
    if (variant === "nginx") {
      return containerTask(name, "nginx:alpine", ["80:80", "443:443"], {}, {
        volumes: ["./nginx.conf:/etc/nginx/nginx.conf:ro"],
      });
    }
    if (variant === "haproxy") {
      return containerTask(name, "haproxy:alpine", ["80:80", "443:443"], {}, {
        volumes: ["./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"],
      });
    }
    return commentTask(name, `${variant} — configure via cloud provider`);
  }

  if (type === "worker") {
    if (variant === "nodejs") {
      const runtime = cfg(config, "runtime", "22");
      const instances = cfg<number>(config, "instances", 2);
      return containerTask(name, `node:${runtime}-alpine`, [], {
        NODE_ENV: "production",
        INSTANCES: String(instances),
      }, {
        working_dir: "/app",
        volumes: [`./${name}:/app`],
        command: "sh -c 'npm install && node index.js'",
      });
    }
    if (variant === "python") {
      const runtime = cfg(config, "runtime", "3.12");
      return containerTask(name, `python:${runtime}-slim`, [], {}, {
        working_dir: "/app",
        volumes: [`./${name}:/app`],
        command: "sh -c 'pip install -r requirements.txt && python main.py'",
      });
    }
    if (variant === "go") {
      return containerTask(name, "golang:1.22-alpine", [], {}, {
        working_dir: "/app",
        volumes: [`./${name}:/app`],
        command: "sh -c 'go build -o worker . && ./worker'",
      });
    }
    if (variant === "rust") {
      return containerTask(name, "rust:1-alpine", [], {}, {
        working_dir: "/app",
        volumes: [`./${name}:/app`],
        command: "sh -c 'cargo build --release && ./target/release/worker'",
      });
    }
    return commentTask(name, `${variant} — deploy via provider CLI`);
  }

  if (type === "api") {
    const port = variant === "grpc" ? "50051" : variant === "graphql" ? "4000" : "3000";
    const instances = cfg<number>(config, "instances", 2);
    return containerTask(name, `your-org/${name}:latest`, [`${port}:${port}`], {
      PORT: port,
      NODE_ENV: "production",
      INSTANCES: String(instances),
    });
  }

  if (type === "cdn" || type === "external" || type === "user") {
    return commentTask(name, "external actor — no container task");
  }

  return commentTask(name, `unknown type "${type}/${variant}"`);
}

export function generateAnsible(nodes: IacNode[], edges: IacEdge[]): string {
  const ordered = topoSort(nodes, edges);
  const tasks = ordered.map(nodeToTask).filter(Boolean);

  const varsBlock = `  vars:
    postgres_password: "change_me_in_vault"
    mysql_password: "change_me_in_vault"
    mongo_password: "change_me_in_vault"
    rabbitmq_password: "change_me_in_vault"`;

  const playbook = [
    HEADER,
    `- name: Deploy archlet diagram services`,
    `  hosts: all`,
    `  become: true`,
    varsBlock,
    `  tasks:`,
    tasks.map((t) => t).join("\n\n"),
  ].join("\n");

  return playbook;
}
