// Docker Compose generator for archlet diagrams
import { sanitizeName, cfg, buildDependsOn, type IacNode, type IacEdge } from "./utils";

const HEADER = `# Generated by archlet — Docker Compose starter template
# Review and harden before production use
version: "3.9"
`;

type ServiceDef = {
  image?: string;
  build?: string;
  ports?: string[];
  environment?: Record<string, string>;
  volumes?: string[];
  command?: string;
  depends_on?: string[];
  comment?: string;
  working_dir?: string;
};

function nodeToService(node: IacNode, deps: string[]): { name: string; def: ServiceDef | null; volume?: string; comment?: string } {
  const name = sanitizeName(node.data.label);
  const variant = node.data.variant ?? "";
  const type = node.type ?? "";
  const config = node.data.config ?? {};

  const base: Partial<ServiceDef> = deps.length ? { depends_on: deps } : {};

  // database
  if (type === "database") {
    if (variant === "postgres") {
      const version = cfg(config, "version", "16");
      return { name, def: { ...base, image: `postgres:${version}`, environment: { POSTGRES_PASSWORD: "change_me", POSTGRES_DB: name }, ports: [`5432:5432`], volumes: [`${name}_data:/var/lib/postgresql/data`] }, volume: name };
    }
    if (variant === "mysql") {
      const version = cfg(config, "version", "8.0");
      return { name, def: { ...base, image: `mysql:${version}`, environment: { MYSQL_ROOT_PASSWORD: "change_me", MYSQL_DATABASE: name }, ports: ["3306:3306"], volumes: [`${name}_data:/var/lib/mysql`] }, volume: name };
    }
    if (variant === "mongodb") {
      const version = cfg(config, "version", "7.0");
      return { name, def: { ...base, image: `mongo:${version}`, environment: { MONGO_INITDB_ROOT_USERNAME: "admin", MONGO_INITDB_ROOT_PASSWORD: "change_me" }, ports: ["27017:27017"], volumes: [`${name}_data:/data/db`] }, volume: name };
    }
    if (variant === "cassandra") {
      return { name, def: { ...base, image: "cassandra:4", ports: ["9042:9042"], volumes: [`${name}_data:/var/lib/cassandra`] }, volume: name };
    }
    // sqlite, dynamodb, unknown db
    return { name, def: null, comment: `# ${name}: ${variant} — not containerizable (use managed service or local file)` };
  }

  // cache
  if (type === "cache") {
    if (variant === "redis") {
      const memGb = cfg<number>(config, "memoryGb", 1);
      const policy = cfg(config, "evictionPolicy", "allkeys-lru");
      return { name, def: { ...base, image: "redis:7-alpine", ports: ["6379:6379"], command: `redis-server --maxmemory ${memGb}gb --maxmemory-policy ${policy}` } };
    }
    if (variant === "memcached") {
      const memMb = cfg<number>(config, "memoryMb", 512);
      return { name, def: { ...base, image: "memcached:alpine", ports: ["11211:11211"], command: `memcached -m ${memMb}` } };
    }
    // keydb, valkey
    return { name, def: { ...base, image: `${variant}:latest`, ports: ["6379:6379"] } };
  }

  // queue
  if (type === "queue") {
    if (variant === "rabbitmq") {
      return { name, def: { ...base, image: "rabbitmq:3-management", ports: ["5672:5672", "15672:15672"], environment: { RABBITMQ_DEFAULT_USER: "admin", RABBITMQ_DEFAULT_PASS: "change_me" } } };
    }
    if (variant === "kafka") {
      const partitions = cfg<number>(config, "partitions", 12);
      return { name, def: { ...base, image: "confluentinc/cp-kafka:7.5.0", ports: ["9092:9092"], environment: { KAFKA_BROKER_ID: "1", KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181", KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092", KAFKA_NUM_PARTITIONS: String(partitions), KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1", KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" }, depends_on: [...(deps ?? []), "zookeeper"] } };
    }
    // sqs, redis-streams, nats — managed or comment
    return { name, def: null, comment: `# ${name}: ${variant} — use managed cloud service` };
  }

  // storage
  if (type === "storage") {
    if (variant === "local-disk") {
      const sizeGb = cfg<number>(config, "sizeGb", 100);
      return { name, def: { ...base, image: "busybox", volumes: [`./data:/data`], command: `sh -c "echo 'Local disk ${sizeGb}GB mounted at /data'; tail -f /dev/null"` } };
    }
    // s3, r2, gcs, azure-blob
    return { name, def: null, comment: `# ${name}: ${variant} — use real cloud object storage provider` };
  }

  // load_balancer
  if (type === "load_balancer") {
    if (variant === "nginx") {
      return { name, def: { ...base, image: "nginx:alpine", ports: ["80:80", "443:443"], volumes: ["./nginx.conf:/etc/nginx/nginx.conf:ro"] } };
    }
    if (variant === "haproxy") {
      return { name, def: { ...base, image: "haproxy:alpine", ports: ["80:80", "443:443"], volumes: ["./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"] } };
    }
    // aws-alb, envoy, cloudflare-lb
    return { name, def: null, comment: `# ${name}: ${variant} — use managed load balancer service` };
  }

  // worker
  if (type === "worker") {
    const instances = cfg<number>(config, "instances", 2);
    if (variant === "nodejs") {
      const runtime = cfg(config, "runtime", "22");
      return { name, def: { ...base, image: `node:${runtime}-alpine`, working_dir: "/app", volumes: [`./${name}:/app`], command: `sh -c "npm install && node index.js"`, environment: { NODE_ENV: "production", INSTANCES: String(instances) } } };
    }
    if (variant === "python") {
      const runtime = cfg(config, "runtime", "3.12");
      return { name, def: { ...base, image: `python:${runtime}-slim`, working_dir: "/app", volumes: [`./${name}:/app`], command: `sh -c "pip install -r requirements.txt && python main.py"` } };
    }
    if (variant === "go") {
      return { name, def: { ...base, image: "golang:1.22-alpine", working_dir: "/app", volumes: [`./${name}:/app`], command: `sh -c "go build -o worker . && ./worker"` } };
    }
    if (variant === "rust") {
      return { name, def: { ...base, image: "rust:1-alpine", working_dir: "/app", volumes: [`./${name}:/app`], command: `sh -c "cargo build --release && ./target/release/worker"` } };
    }
    // aws-lambda, cf-workers
    return { name, def: null, comment: `# ${name}: ${variant} — deploy via provider CLI` };
  }

  // api
  if (type === "api") {
    const port = variant === "grpc" ? "50051" : variant === "graphql" ? "4000" : "3000";
    const instances = cfg<number>(config, "instances", 2);
    return { name, def: { ...base, build: `./${name}`, image: `your-org/${name}:latest`, ports: [`${port}:${port}`], environment: { PORT: port, NODE_ENV: "production", INSTANCES: String(instances) } } };
  }

  // cdn
  if (type === "cdn") {
    return { name, def: null, comment: `# ${name}: Use a real CDN provider (Cloudflare/CloudFront) in production` };
  }

  // user / external
  if (type === "user") {
    return { name, def: null, comment: `# ${name}: External client — no container needed` };
  }
  if (type === "external") {
    return { name, def: null, comment: `# ${name}: External service — configure via env vars` };
  }

  return { name, def: null, comment: `# ${name}: TODO — unknown service type "${type}/${variant}"` };
}

function renderService(name: string, def: ServiceDef): string {
  const lines: string[] = [`  ${name}:`];
  if (def.image) lines.push(`    image: ${def.image}`);
  if (def.build) lines.push(`    build: ${def.build}`);
  if (def.command) lines.push(`    command: >-\n      ${def.command}`);
  if (def.working_dir) lines.push(`    working_dir: ${def.working_dir}`);
  if (def.ports?.length) {
    lines.push("    ports:");
    for (const p of def.ports) lines.push(`      - "${p}"`);
  }
  if (def.environment && Object.keys(def.environment).length) {
    lines.push("    environment:");
    for (const [k, v] of Object.entries(def.environment)) lines.push(`      ${k}: ${v}`);
  }
  if (def.volumes?.length) {
    lines.push("    volumes:");
    for (const v of def.volumes) lines.push(`      - ${v}`);
  }
  if (def.depends_on?.length) {
    lines.push("    depends_on:");
    for (const d of def.depends_on) lines.push(`      - ${d}`);
  }
  return lines.join("\n");
}

export function generateDockerCompose(nodes: IacNode[], edges: IacEdge[]): string {
  const deps = buildDependsOn(nodes, edges);
  const services: string[] = [];
  const comments: string[] = [];
  const volumes: string[] = [];

  // Add zookeeper if kafka present
  const hasKafka = nodes.some((n) => n.type === "queue" && n.data.variant === "kafka");
  if (hasKafka) {
    services.push(renderService("zookeeper", {
      image: "confluentinc/cp-zookeeper:7.5.0",
      ports: ["2181:2181"],
      environment: { ZOOKEEPER_CLIENT_PORT: "2181", ZOOKEEPER_TICK_TIME: "2000" },
    }));
  }

  for (const node of nodes) {
    const nodeDeps = deps.get(node.id) ?? [];
    const result = nodeToService(node, nodeDeps);
    if (result.def) {
      services.push(renderService(result.name, result.def));
      if (result.volume) volumes.push(`  ${result.name}_data:`);
    } else if (result.comment) {
      comments.push(result.comment);
    }
  }

  const parts: string[] = [HEADER];
  if (services.length) {
    parts.push("services:");
    parts.push(services.join("\n\n"));
  } else {
    parts.push("services: {}  # No containerizable services found");
  }
  if (volumes.length) {
    parts.push("\nvolumes:");
    parts.push(volumes.join("\n"));
  }
  if (comments.length) {
    parts.push("\n# --- Non-containerized services ---");
    parts.push(comments.join("\n"));
  }
  return parts.join("\n");
}
