// Kubernetes manifests generator for archlet diagrams
import { sanitizeName, cfg, type IacNode, type IacEdge } from "./utils";

const HEADER = `# Generated by archlet — Kubernetes manifests starter
# Apply: kubectl apply -f archlet.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: archlet
  labels:
    app.kubernetes.io/managed-by: archlet
`;

const MANAGED_BY = "app.kubernetes.io/managed-by: archlet";

function cpuRequest(cpu: number): string {
  return cpu >= 1 ? `${cpu}` : `${Math.round(cpu * 1000)}m`;
}

function deployment(name: string, image: string, port: number, replicas: number, cpu: number, memMb: number, envVars: Record<string, string> = {}): string {
  const envBlock = Object.entries(envVars).length
    ? "        env:\n" + Object.entries(envVars).map(([k, v]) => `          - name: ${k}\n            value: "${v}"`).join("\n")
    : "";
  return `---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  namespace: archlet
  labels:
    app: ${name}
    ${MANAGED_BY}
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
        - name: ${name}
          image: ${image}
          ports:
            - containerPort: ${port}
${envBlock}
          resources:
            requests:
              cpu: "${cpuRequest(cpu)}"
              memory: "${memMb}Mi"
            limits:
              cpu: "${cpuRequest(cpu * 2)}"
              memory: "${memMb * 2}Mi"`;
}

function service(name: string, port: number, type = "ClusterIP"): string {
  return `---
apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: archlet
  labels:
    app: ${name}
    ${MANAGED_BY}
spec:
  type: ${type}
  selector:
    app: ${name}
  ports:
    - port: ${port}
      targetPort: ${port}`;
}

function statefulSet(name: string, image: string, port: number, storageGb: number, replicas: number, envVars: Record<string, string> = {}): string {
  const envBlock = Object.entries(envVars).length
    ? "        env:\n" + Object.entries(envVars).map(([k, v]) => `          - name: ${k}\n            value: "${v}"`).join("\n")
    : "";
  return `---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${name}
  namespace: archlet
  labels:
    app: ${name}
    ${MANAGED_BY}
spec:
  serviceName: ${name}
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
        - name: ${name}
          image: ${image}
          ports:
            - containerPort: ${port}
${envBlock}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: ${storageGb}Gi`;
}

function headlessService(name: string, port: number): string {
  return `---
apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: archlet
  labels:
    app: ${name}
    ${MANAGED_BY}
spec:
  clusterIP: None
  selector:
    app: ${name}
  ports:
    - port: ${port}
      targetPort: ${port}`;
}

function pvc(name: string, storageGb: number): string {
  return `---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${name}-pvc
  namespace: archlet
  labels:
    ${MANAGED_BY}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: ${storageGb}Gi`;
}

function nodeToManifests(node: IacNode, edges: IacEdge[]): string {
  const name = sanitizeName(node.data.label);
  const variant = node.data.variant ?? "";
  const type = node.type ?? "";
  const config = node.data.config ?? {};

  // Build env vars from incoming edges (producer service DNS)
  const incomingEdges = edges.filter((e) => e.target === node.id);
  const envFromEdges: Record<string, string> = {};

  if (type === "api" || type === "worker") {
    const instances = cfg<number>(config, "instances", 2);
    const cpu = cfg<number>(config, "cpu", 1);
    const memMb = cfg<number>(config, "memoryMb", 512);

    let image = `your-org/${name}:latest`;
    let port = 3000;
    if (variant === "graphql") port = 4000;
    if (variant === "grpc") port = 50051;
    if (variant === "nodejs") image = `node:22-alpine`;
    if (variant === "python") image = `python:3.12-slim`;
    if (variant === "go") image = `golang:1.22-alpine`;
    if (variant === "rust") image = `rust:1-alpine`;
    if (variant === "aws-lambda") return `# ${name}: aws-lambda — deploy via AWS SAM or Serverless Framework`;
    if (variant === "cloudflare-workers") return `# ${name}: cloudflare-workers — deploy via Wrangler CLI`;

    return [
      deployment(name, image, port, instances, cpu, memMb, envFromEdges),
      service(name, port),
    ].join("\n");
  }

  if (type === "database") {
    if (variant === "postgres") {
      const storageGb = cfg<number>(config, "storageGb", 50);
      const replicas = cfg<number>(config, "replicas", 1);
      const version = cfg(config, "version", "16");
      return [
        statefulSet(name, `postgres:${version}`, 5432, storageGb, replicas, {
          POSTGRES_PASSWORD: "CHANGE_ME",
          POSTGRES_DB: name,
        }),
        headlessService(name, 5432),
      ].join("\n");
    }
    if (variant === "mysql") {
      const storageGb = cfg<number>(config, "storageGb", 50);
      const replicas = cfg<number>(config, "replicas", 1);
      const version = cfg(config, "version", "8.0");
      return [
        statefulSet(name, `mysql:${version}`, 3306, storageGb, replicas, {
          MYSQL_ROOT_PASSWORD: "CHANGE_ME",
          MYSQL_DATABASE: name,
        }),
        headlessService(name, 3306),
      ].join("\n");
    }
    if (variant === "mongodb") {
      const storageGb = cfg<number>(config, "storageGb", 50);
      const replicas = cfg<number>(config, "replicaSet", 3);
      const version = cfg(config, "version", "7.0");
      return [
        statefulSet(name, `mongo:${version}`, 27017, storageGb, replicas, {
          MONGO_INITDB_ROOT_USERNAME: "admin",
          MONGO_INITDB_ROOT_PASSWORD: "CHANGE_ME",
        }),
        headlessService(name, 27017),
      ].join("\n");
    }
    if (variant === "cassandra") {
      return [
        statefulSet(name, "cassandra:4", 9042, 100, 3),
        headlessService(name, 9042),
      ].join("\n");
    }
    return `# ${name}: ${variant} — use managed cloud database service`;
  }

  if (type === "cache") {
    if (variant === "redis" || variant === "keydb" || variant === "valkey") {
      const memGb = cfg<number>(config, "memoryGb", 1);
      const image = variant === "redis" ? "redis:7-alpine" : `${variant}:latest`;
      return [
        statefulSet(name, image, 6379, Math.max(1, memGb), 1),
        headlessService(name, 6379),
      ].join("\n");
    }
    if (variant === "memcached") {
      return [
        deployment(name, "memcached:alpine", 11211, 1, 0.5, 512),
        service(name, 11211),
      ].join("\n");
    }
    return `# ${name}: ${variant} — no direct K8s mapping`;
  }

  if (type === "queue") {
    if (variant === "rabbitmq") {
      return [
        statefulSet(name, "rabbitmq:3-management", 5672, 10, 1, {
          RABBITMQ_DEFAULT_USER: "admin",
          RABBITMQ_DEFAULT_PASS: "CHANGE_ME",
        }),
        headlessService(name, 5672),
      ].join("\n");
    }
    if (variant === "kafka") {
      const partitions = cfg<number>(config, "partitions", 12);
      const replFactor = cfg<number>(config, "replicationFactor", 3);
      return [
        statefulSet(name, "confluentinc/cp-kafka:7.5.0", 9092, 50, replFactor, {
          KAFKA_BROKER_ID: "1",
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181",
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092",
          KAFKA_NUM_PARTITIONS: String(partitions),
        }),
        headlessService(name, 9092),
      ].join("\n");
    }
    return `# ${name}: ${variant} — use managed cloud queue service`;
  }

  if (type === "storage") {
    if (variant === "local-disk") {
      const sizeGb = cfg<number>(config, "sizeGb", 100);
      return pvc(name, sizeGb);
    }
    return `# ${name}: ${variant} — use cloud object storage (not a K8s PVC)`;
  }

  if (type === "load_balancer") {
    if (variant === "nginx") {
      return [
        deployment(name, "nginx:alpine", 80, 2, 0.5, 256),
        service(name, 80, "LoadBalancer"),
      ].join("\n");
    }
    if (variant === "haproxy") {
      return [
        deployment(name, "haproxy:alpine", 80, 2, 0.5, 256),
        service(name, 80, "LoadBalancer"),
      ].join("\n");
    }
    return `# ${name}: ${variant} — configure via cloud provider ingress controller`;
  }

  if (type === "cdn" || type === "external" || type === "user") {
    return `# ${name}: external / managed — no K8s manifest needed`;
  }

  return `# ${name}: TODO — unknown type "${type}/${variant}"`;
}

export function generateKubernetes(nodes: IacNode[], edges: IacEdge[]): string {
  const manifests: string[] = [HEADER];
  for (const node of nodes) {
    const manifest = nodeToManifests(node, edges);
    if (manifest.trim()) manifests.push(manifest);
  }
  return manifests.join("\n");
}
