// Terraform AWS generator for archlet diagrams
import { sanitizeName, cfg, type IacNode, type IacEdge } from "./utils";
import { getCloudService } from "@archlet/shared";

const HEADER = `# Generated by archlet — Terraform AWS starter template
# Review variables, IAM, networking before production use

terraform {
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  default = "us-east-1"
}
`;

function dbInstanceClass(connectionPool: number): string {
  if (connectionPool >= 500) return "db.r6g.xlarge";
  if (connectionPool >= 200) return "db.t3.large";
  return "db.t3.micro";
}

function cacheNodeType(memoryGb: number): string {
  if (memoryGb >= 8) return "cache.r6g.large";
  if (memoryGb >= 2) return "cache.t3.medium";
  return "cache.t3.micro";
}

function lambdaMemoryArchitecture(memoryMb: number): string {
  return memoryMb >= 1024 ? "arm64" : "x86_64";
}

function renderBlock(type: string, name: string, body: string): string {
  return `resource "${type}" "${name}" {\n${body}\n}`;
}

function attr(key: string, value: string | number | boolean, indent = 2): string {
  const pad = " ".repeat(indent);
  if (typeof value === "string") return `${pad}${key} = "${value}"`;
  return `${pad}${key} = ${value}`;
}

function block(name: string, body: string, indent = 2): string {
  const pad = " ".repeat(indent);
  const inner = body.split("\n").map((l) => (l.trim() ? "  " + l : l)).join("\n");
  return `${pad}${name} {\n${inner}\n${pad}}`;
}

function nodeToHcl(node: IacNode, deps: Map<string, string[]>): string | null {
  const name = sanitizeName(node.data.label);
  const variant = node.data.variant ?? "";
  const type = node.type ?? "";
  const config = node.data.config ?? {};

  if (type === "database") {
    if (variant === "postgres" || variant === "mysql") {
      const engine = variant === "postgres" ? "postgres" : "mysql";
      const engineVer = variant === "postgres"
        ? cfg(config, "version", "16")
        : cfg(config, "version", "8.0");
      const storageGb = cfg<number>(config, "storageGb", 50);
      const pool = cfg<number>(config, "connectionPool", 100);
      const replicas = cfg<number>(config, "replicas", 1);
      const multiAz = replicas > 1;
      const body = [
        attr("identifier", name),
        attr("engine", engine),
        attr("engine_version", engineVer),
        attr("instance_class", dbInstanceClass(pool)),
        attr("allocated_storage", storageGb),
        attr("username", "admin"),
        attr("password", "CHANGE_ME_USE_SECRETS_MANAGER"),
        attr("multi_az", multiAz),
        attr("skip_final_snapshot", true),
        attr("deletion_protection", false),
        `\n  tags = { Name = "${name}", ManagedBy = "archlet" }`,
      ].join("\n");
      return renderBlock("aws_db_instance", name, body);
    }

    if (variant === "mongodb") {
      return `# ${name}: MongoDB — use aws_docdb_cluster (DocumentDB) or self-hosted EC2\n# TODO: add aws_docdb_cluster resource for "${name}"`;
    }

    if (variant === "dynamodb") {
      const billing = cfg(config, "billingMode", "ondemand");
      const rcu = cfg<number>(config, "rcu", 5);
      const wcu = cfg<number>(config, "wcu", 5);
      const billingMode = billing === "ondemand" ? "PAY_PER_REQUEST" : "PROVISIONED";
      const lines = [
        attr("name", name),
        attr("billing_mode", billingMode),
      ];
      if (billingMode === "PROVISIONED") {
        lines.push(attr("read_capacity", rcu));
        lines.push(attr("write_capacity", wcu));
      }
      lines.push(`  hash_key = "id"`);
      lines.push(`  attribute {\n    name = "id"\n    type = "S"\n  }`);
      lines.push(`  tags = { Name = "${name}", ManagedBy = "archlet" }`);
      return renderBlock("aws_dynamodb_table", name, lines.join("\n"));
    }

    return `# ${name}: ${variant} — no direct AWS managed service mapping; deploy on EC2`;
  }

  if (type === "cache") {
    if (variant === "redis" || variant === "keydb" || variant === "valkey") {
      const memGb = cfg<number>(config, "memoryGb", 1);
      const replicas = cfg<number>(config, "replicas", 1);
      const body = [
        attr("cluster_id", name),
        attr("engine", "redis"),
        attr("engine_version", "7.0"),
        attr("node_type", cacheNodeType(memGb)),
        attr("num_cache_nodes", 1),
        attr("parameter_group_name", "default.redis7"),
        `  tags = { Name = "${name}", ManagedBy = "archlet" }`,
        replicas > 1 ? `  # TODO: use aws_elasticache_replication_group for ${replicas} replicas` : "",
      ].filter(Boolean).join("\n");
      return renderBlock("aws_elasticache_cluster", name, body);
    }
    if (variant === "memcached") {
      const memMb = cfg<number>(config, "memoryMb", 512);
      const body = [
        attr("cluster_id", name),
        attr("engine", "memcached"),
        attr("node_type", cacheNodeType(memMb / 1024)),
        attr("num_cache_nodes", 1),
        attr("parameter_group_name", "default.memcached1.6"),
        `  tags = { Name = "${name}", ManagedBy = "archlet" }`,
      ].join("\n");
      return renderBlock("aws_elasticache_cluster", name, body);
    }
    return `# ${name}: ${variant} — no direct AWS mapping`;
  }

  if (type === "queue") {
    if (variant === "sqs") {
      const fifo = cfg<boolean>(config, "fifo", false);
      const vis = cfg<number>(config, "visibilityTimeoutSec", 30);
      const qName = fifo ? `${name}.fifo` : name;
      const body = [
        attr("name", qName),
        attr("visibility_timeout_seconds", vis),
        fifo ? attr("fifo_queue", true) : "",
        `  tags = { Name = "${name}", ManagedBy = "archlet" }`,
      ].filter(Boolean).join("\n");
      return renderBlock("aws_sqs_queue", name, body);
    }
    if (variant === "kafka") {
      const replFactor = cfg<number>(config, "replicationFactor", 3);
      const body = [
        attr("cluster_name", name),
        attr("kafka_version", "3.5.1"),
        attr("number_of_broker_nodes", replFactor),
        block("broker_node_group_info", [
          attr("instance_type", "kafka.m5.large", 0),
          attr("client_subnets", `["subnet-CHANGE_ME"]`, 0),
          attr("storage_info", `{\n    ebs_storage_info = { volume_size = 100 }\n  }`, 0),
        ].join("\n")),
        `  tags = { Name = "${name}", ManagedBy = "archlet" }`,
      ].join("\n");
      return renderBlock("aws_msk_cluster", name, body);
    }
    return `# ${name}: ${variant} — use appropriate AWS messaging service`;
  }

  if (type === "storage") {
    if (variant === "s3" || variant === "r2") {
      const note = variant === "r2" ? "\n  # NOTE: R2 uses Cloudflare provider — swap aws provider for cloudflare/cloudflare" : "";
      const body = [
        attr("bucket", name),
        `  force_destroy = false${note}`,
        `  tags = { Name = "${name}", ManagedBy = "archlet" }`,
      ].join("\n");
      return renderBlock("aws_s3_bucket", name, body);
    }
    return `# ${name}: ${variant} — use appropriate cloud storage resource`;
  }

  if (type === "load_balancer") {
    if (variant === "aws-alb") {
      const lbBlock = renderBlock("aws_lb", name, [
        attr("name", name),
        attr("internal", false),
        attr("load_balancer_type", "application"),
        `  subnets         = ["subnet-CHANGE_ME_1", "subnet-CHANGE_ME_2"]`,
        `  tags = { Name = "${name}", ManagedBy = "archlet" }`,
      ].join("\n"));
      const tgBlock = renderBlock("aws_lb_target_group", `${name}_tg`, [
        attr("name", `${name}-tg`),
        attr("port", 80),
        attr("protocol", "HTTP"),
        `  vpc_id = "vpc-CHANGE_ME"`,
      ].join("\n"));
      const listenerBlock = renderBlock("aws_lb_listener", `${name}_listener`, [
        `  load_balancer_arn = aws_lb.${name}.arn`,
        attr("port", 80),
        attr("protocol", "HTTP"),
        `  default_action {\n    type             = "forward"\n    target_group_arn = aws_lb_target_group.${name}_tg.arn\n  }`,
      ].join("\n"));
      return [lbBlock, tgBlock, listenerBlock].join("\n\n");
    }
    return `# ${name}: ${variant} — deploy load balancer via provider-specific resources`;
  }

  if (type === "cdn") {
    if (variant === "cloudfront") {
      const priceClass = cfg(config, "priceClass", "100");
      const body = [
        `  origin {\n    domain_name = "CHANGE_ME.s3.amazonaws.com"\n    origin_id   = "${name}_origin"\n  }`,
        attr("enabled", true),
        `  default_cache_behavior {\n    allowed_methods        = ["GET", "HEAD"]\n    cached_methods         = ["GET", "HEAD"]\n    target_origin_id       = "${name}_origin"\n    viewer_protocol_policy = "redirect-to-https"\n    forwarded_values {\n      query_string = false\n      cookies { forward = "none" }\n    }\n  }`,
        attr("price_class", `PriceClass_${priceClass}`),
        `  restrictions {\n    geo_restriction { restriction_type = "none" }\n  }`,
        `  viewer_certificate { cloudfront_default_certificate = true }`,
        `  tags = { Name = "${name}", ManagedBy = "archlet" }`,
      ].join("\n");
      return renderBlock("aws_cloudfront_distribution", name, body);
    }
    return `# ${name}: ${variant} — use provider-specific CDN resources`;
  }

  if (type === "worker") {
    if (variant === "aws-lambda") {
      const memMb = cfg<number>(config, "memoryMb", 512);
      const timeout = cfg<number>(config, "timeoutSec", 30);
      const body = [
        attr("function_name", name),
        attr("runtime", "nodejs22.x"),
        attr("handler", "index.handler"),
        attr("memory_size", memMb),
        attr("timeout", timeout),
        attr("architectures", `["${lambdaMemoryArchitecture(memMb)}"]`),
        `  role          = "arn:aws:iam::ACCOUNT_ID:role/CHANGE_ME_lambda_role"`,
        `  filename      = "${name}.zip"  # package your function code`,
        `  tags = { Name = "${name}", ManagedBy = "archlet" }`,
      ].join("\n");
      return renderBlock("aws_lambda_function", name, body);
    }
    return `# ${name}: ${variant} — deploy via EC2, ECS, or EKS`;
  }

  if (type === "api") {
    if (variant === "api-gateway") {
      const body = [
        attr("name", name),
        attr("description", `API Gateway managed by archlet`),
        `  tags = { Name = "${name}", ManagedBy = "archlet" }`,
      ].join("\n");
      return renderBlock("aws_api_gateway_rest_api", name, body);
    }
    return `# ${name}: ${variant} — deploy via ECS/EKS or EC2 with target group`;
  }

  if (type === "user" || type === "external") {
    // Cloud Services Phase 4: detect cloud-services catalog variant and emit stub
    const svc = getCloudService(variant);
    if (svc) {
      return [
        `# ${name}: ${svc.name} (${svc.cloud.toUpperCase()} ${svc.category})`,
        `# See: ${svc.docsUrl}`,
        `# resource "${svc.cloud}_..." "${name}" {`,
        `#   # TODO: configure ${svc.category} service — fields depend on resource type`,
        `# }`,
      ].join("\n");
    }
    return `# ${name}: external actor — no AWS resource needed`;
  }

  return `# ${name}: TODO — unknown type "${type}/${variant}"`;
}

export function generateTerraformAws(nodes: IacNode[], edges: IacEdge[]): string {
  const deps = new Map<string, string[]>();
  for (const e of edges) {
    if (!deps.has(e.target)) deps.set(e.target, []);
    deps.get(e.target)!.push(e.source);
  }

  const blocks: string[] = [HEADER];
  for (const node of nodes) {
    const hcl = nodeToHcl(node, deps);
    if (hcl) blocks.push(hcl);
  }
  return blocks.join("\n\n");
}
